sprint_2
alexweb79/middle.messenger.praktikum.yandex pull request #2
Opened 2022-11-06 15:09 UTC by alexweb79

2022-11-06 15:45 UTC, podlovchenko requested changes
Привет, есть несколько замечаний по работе
1. Валидация не работает в соответствии с заданием
<img width="751" alt="Снимок экрана 2022-11-06 в 18 34 58" src="https://user-images.githubusercontent.com/22602747/200179893-8216266d-defb-4836-8868-cb38e7be9192.png">
2. Есть ошибки типизации, попробуй выполнить команду `npx tsc --noEmit`
3. Добавить типизацию пропсов компонентов

2022-11-06 15:45 UTC, podlovchenko commented on .parcelrc
> +  //}
Закомментированный код лучше не оставлять в проекте

2022-11-06 15:45 UTC, podlovchenko commented on package.json
> +    "start": "parcel src/index.html --dist-dir dist --port 3000",
Команда старт должна запускать сервер на express

2022-11-06 15:45 UTC, podlovchenko commented on server.js
>  const port = 3000;
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через переменное окружение:
process.env.PORT || PORT;
https://nodejs.org/dist/latest-v8.x/docs/api/process.html

2022-11-06 15:45 UTC, podlovchenko commented on src/services/Block.ts
> +export default class Block {
Было бы здорово сделать класс Block [дженериком](https://www.typescriptlang.org/docs/handbook/2/generics.html), так будет возможность точно передать в базовый блок, тип пропсов наследников
Пример:
```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}
```

2022-11-06 15:45 UTC, podlovchenko commented on src/services/Block.ts
> +  _createResources() {
Для приватных методов и свойств не хватает модификатора private

2022-11-06 15:45 UTC, podlovchenko commented on src/services/HTTPTransport.ts
> +type OptionsWithoutMethod = { data?: any };
Можно использовать дженерик Omit https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys

2022-11-06 15:45 UTC, podlovchenko commented on src/services/HTTPTransport.ts
> +enum METHOD {
enum обычно именуется в PascalCase

2022-11-06 15:45 UTC, podlovchenko commented on src/services/HTTPTransport.ts
> +};
Необходимо добавить возможность прокидывать заголовки и timeout

2022-11-06 15:45 UTC, podlovchenko commented on src/services/HTTPTransport.ts
> +  get(url: string, options: OptionsWithoutMethod = {}): Promise<XMLHttpRequest> {
Было бы классно сделать методы дженериками, чтобы можно было извне определить тип входных и выходных данных

2022-11-06 15:45 UTC, podlovchenko commented on src/styles/chat.scss
>            span {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-11-06 15:45 UTC, podlovchenko commented on src/services/EventBus.ts
> +export default class EventBus {
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая статья на эту тему
https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

2022-11-07 19:12 UTC, alexweb79 commented
Привет! Замечания поправил, посмотри пожалуйста.

2022-11-07 19:14 UTC, alexweb79 commented on src/services/Block.ts
> +export default class Block {
Не получилось сделать дженериком, тяжеловато доходит, может есть еще что то почитать по ним ?

2022-11-07 19:14 UTC, alexweb79 commented on package.json
> +    "start": "parcel src/index.html --dist-dir dist --port 3000",
тесты не пропускали с сервером на старте, пока вернул обратно

2022-11-08 11:32 UTC, podlovchenko commented
Привет, по валидации сейчас некорректно работает:
1. Имя и фамилия, проходит Test10 (не должно проходить, так как по заданию не должно быть цифр), не проходит Тест (должно проходить, по заданию кириллица разрешена)
2. email, проходит test@тест.ru (не должно, по заданию только латиница)
3. phone, проходит 1234567890тест (не должно, по заданию только цифры)

О дженериках лучше всего почитать в документации https://www.typescriptlang.org/docs/handbook/2/generics.html, это не обязательный пункт

Какая ошибка была со стартом сервера?

2022-11-08 15:18 UTC, alexweb79 commented
Привет!

Локально со стартом сервера не было ошибки, при тестах вылетала:
<img width="502" alt="image" src="https://user-images.githubusercontent.com/15979347/200603181-8148aacc-5ff5-4339-8e27-bf7069a46b7d.png">

2022-11-08 18:21 UTC, podlovchenko commented
Сейчас падают чеки нетлифай и там сейчас неактуальная версия, нужно обновить
Для настройки сборки и запуска приложения нужно добавить netlify.toml https://docs.netlify.com/configure-builds/file-based-configuration/
Попробуй сделать в команде start сборку проекта и запуск сервера

2022-11-08 19:49 UTC, alexweb79 commented
Все отработало.
Нужно еще раз отправить новую версию на ревью ? (последняя осталась)

2022-11-09 18:31 UTC, podlovchenko commented
В netlify.toml необходимо добавить [[redirects]] на index.html, чтобы отдавались все страницы, сейчас page not found, поправь, пожалуйста, к следующему спринту
Работу принимаю

2022-11-10 06:45 UTC, alexweb79 commented
да, я понял, в netlify.toml не хватает:
```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```
Спасибо.

2022-11-10 06:56 UTC, merged